version: '3.4'

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend/:/usr/share/nginx/html:rw
    ports:
      - "80"

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend/:/var/www/html:rw
    ports:
      - "5000:80"

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306"
    env_file:
      - ./config/secrets.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    env_file:
      - ./config/secrets.env
      - ./config/phpmyadmin.env
